objc_library(
    name = "TeleFlow",
    srcs = glob([
        "Sources/*.swift",
        "Sources/*.m",
    ]),
    enable_modules = True,
    module_name = "TeleFlow",
    visibility = ["//visibility:public"],
    sdk_frameworks = [
        "UIKit",
        "Foundation",
    ],
    uses_swift = True,
)
